### ISSUE TITLE
Cannot Go Up Staircases (going down works fine)

### ISSUE THREAD

**Issue by JGelfand** [gwathlobal/CotD#4]
I'm playing on the 64 bit windows release. To go down staircases (labelled slopes) I can press >, then the direction of the stair. I can go up and down in down in water via < and > just fine. I can get out of water via < and a direction when at the edge. However, when I try to go up a staircase by pressing < and the direction of the staircase, it always moves me onto the staircase at the same elevation instead. 

This renders satanist completely unplayable (since you start in a basement), among other things.

**Comment by red-kangaroo** [comment]
You don't need to press < to go up a staircase. Just walk onto the stairs, then walk in the direction the stairs are rising (where-ever there is unblocked floor upstairs) and you will be moved upstairs. The same works for going downstairs, without pressing >.

The < and > commands are mostly useful when swimming or flying.

**Comment by gwathlobal** [comment]
Indeed it works as intended. There are no stairs in the game so far - only ramps (if we take Dwarf Fortress terminology). To go up a ramp (slope) you need to simply go in the direction of the wall and you will end up on the floor above.
While there are no ramps in water, the same rule applies here as well - to get out of water (when you are on the Z level just below the surface) you move into the shore wall and you get forward and up.

**Comment by JGelfand** [comment]
I guess I should change the bug report, then. After attempting to use ramps in the way you described, I can indeed use down ramps without pressing > at all. I can also get out of water in the way you described. Up ramps in buildings do not work, regardless. In order to make sure that we both understand what I'm trying to do here (maybe I'm doing it wrong?) I've attached a video clip of me trying to go up an up ramp.


[The City of the Damned 1_8_2018 11_41_17 AM.zip](https://github.com/gwathlobal/CotD/files/1612676/The.City.of.the.Damned.1_8_2018.11_41_17.AM.zip)

**Comment by gwathlobal** [comment]
Ok, a question - did you move north, west or south in the attached video?
You should climb up if you move west as all the following conditions are met:
1) on your Z level to the west, there is a wall that blocks movement, 
2) you are standing on a slope, 
3) on the Z level above you the tile to the west is empty, 

So if you move west you will actually find yourself up and west.
You can't go north to move up and north as the tile on the Z level above to the north is blocked by a wall.
You can't go south to move up and south as the tile on your Z level to the south is unblocked so you move there as normal instead of using the slope to go up.

**Comment by JGelfand** [comment]
Alright- I have figured out how to climb slopes now. Thanks for the help.
