### ISSUE TITLE
In campaign mode, there is a great incidence of angels losing if they are delayed

### ISSUE THREAD

**Issue by Sofistico** [gwathlobal/CotD#6]
When i play as an angel it is just defeat after defeat when the angel faction has to go someplace when the party already began, i don't know if it is a feature or what, but it's weird.

Image for illustration:

![image](https://user-images.githubusercontent.com/59299346/90088534-8bdf8000-dcf5-11ea-8544-7f71393031c5.png)

**Comment by gwathlobal** [comment]
Well, the issue here is that you arrive delayed so the scenario starts without you and progresses for 100+ turns. This means that rivaling faction (in this case, demons) can achieve their objectives even before you even appear on the map (in this mission, the demons managed to gather the required number of flesh points). 

What I can do here is reduce the delay before arrival so that it is less likely that the enemies are able to complete the mission without you, but the probability that this happens will still be above zero.

**Comment by Sofistico** [comment]
There isn't a problem if i lose before arriving, but it feels weird when i arrive having just 10 turns to make a stand, it makes it a little unfair.

For exemple, in a Demonic thing where they have to place sigils, they go there and do they stuff and if the angels arrive late for the party, they will have realllllllly a few turns to make a difference.

I don't know if is a question of balance or if you think this is what should happen, but i agree with you that lowering the turns need will help a lot to make it an struggle to win, rather than an insta win scenario.

**Comment by gwathlobal** [comment]
Ok, I lowered the delay before arrival in 2.0.2. Let's see how it goes now.
